default_install_hook_types: [pre-push]
default_stages: [pre-push]

repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff - check code
        entry: uv run ruff check .
        language: system
        pass_filenames: false
        always_run: true

      - id: ruff-format
        name: Ruff - check formatting
        entry: uv run ruff format --check .
        language: system
        pass_filenames: false
        always_run: true

      - id: mypy
        name: Mypy - check types
        entry: uv run mypy .
        language: system
        pass_filenames: false
        always_run: true

      - id: pytest
        name: Pytest - tests
        entry: uv run pytest
        language: system
        pass_filenames: false
        always_run: true