[project]
name = "life-os"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    "pre-commit>=4.3.0",
    "pytest>=8.4.2",
    "ruff>=0.16.10",
]

[tool.basedpyright]
reportMissingImports = "error"

[tool.pytest.ini_options]
pythonpath = ["."]
